### Tokenized Model

In [353]:
import gensim.models as g
import codecs
from scipy import spatial
import os
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from collections import OrderedDict
from sklearn.linear_model import LogisticRegression
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

from sklearn.model_selection import RandomizedSearchCV
import lightgbm as lgb
from keras.models import Sequential
from keras.layers import Dense, Activation,Dropout
from sklearn.metrics import f1_score

In [355]:
def train_test_split(data,labels,n_class,tr_cut):
    data_train = data[:round(tr_cut*(data.shape[0]))]
    labels_train = labels[:round(tr_cut*(labels.shape[0]))]
    data_test = data[round(tr_cut*(data.shape[0])):]
    labels_test = labels[round(tr_cut*(labels.shape[0])):]
    class_weight=compute_class_weight('balanced', np.arange(0,n_class), labels)
    cw_dict = {}
    for i in range(len(class_weight)):
        cw_dict[i] = class_weight[i]
    return data_train,labels_train,data_test,labels_test,cw_dict
        
def log_reg_model(data_train,labels_train,data_test,labels_test,n_class,cw_dict):
    if n_class>2:
        log_reg = LogisticRegression(multi_class='multinomial',solver='lbfgs',n_jobs=-1,class_weight=cw_dict)
    else:
        log_reg = LogisticRegression(class_weight=cw_dict,n_jobs=-1,solver='lbfgs')
    log_reg.fit(data_train,labels_train)
    print("Training accuracy-")
    print(accuracy_score(labels_train,log_reg.predict(data_train)))
    print("Testing accuracy-")
    print(accuracy_score(labels_test,log_reg.predict(data_test)))
    print("Confusion matrix -")
    print(confusion_matrix(labels_test,log_reg.predict(data_test)))
    print('true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]')
    print("Precision and recall - ")
    print(precision_score(labels_test,log_reg.predict(data_test)))
    print(recall_score(labels_test,log_reg.predict(data_test)))
    print("f1-score - ")
    print(f1_score(labels_test,log_reg.predict(data_test)))
    return log_reg

def rf_model(data_train,labels_train,data_test,labels_test,class_weight):
    rand_f_mdl = RandomForestClassifier(class_weight=class_weight,max_depth=40,max_features=240,n_estimators=200,n_jobs=-1)
    rand_f_mdl.fit(data_train,labels_train)
    print("Training accuracy-")
    print(accuracy_score(labels_train,rand_f_mdl.predict(data_train)))
    print("Testing accuracy-")
    print(accuracy_score(labels_test,rand_f_mdl.predict(data_test)))
    print("Confusion matrix -")
    print(confusion_matrix(labels_test,rand_f_mdl.predict(data_test)))
    print('true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]')
    print("Precision and recall - ")
    print(precision_score(labels_test,rand_f_mdl.predict(data_test)))
    print(recall_score(labels_test,rand_f_mdl.predict(data_test)))
    print("f1-score - ")
    print(f1_score(labels_test,rand_f_mdl.predict(data_test)))
    return rand_f_mdl

def threshold(x):
    labels=[]
    for i in x:
        if i>=.55:       
            labels.append(1)
        else:  
            labels.append(0)
    return labels




def light_gbm_model(data_train,labels_train,data_test,labels_test,class_weight):
    d_train = lgb.Dataset(data_train, label=labels_train)
    params = {}
    params['learning_rate'] = 0.003
    params['boosting_type'] = 'gbdt'
    params['objective'] = 'binary'
    params['metric'] = 'binary_logloss'
    params['sub_feature'] = 0.5
    params['num_leaves'] = 40
    params['min_data'] = 50
    params['max_depth'] = 50
    params['is_unbalance'] = True
    #params['class_weight']=class_weight
    clf = lgb.train(params, d_train, 1000)

    
    print("Training accuracy-")
    print(accuracy_score(labels_train,threshold(clf.predict(data_train))))
    print("Testing accuracy-")
    print(accuracy_score(labels_test,threshold(clf.predict(data_test))))
    print("Confusion matrix -")
    print(confusion_matrix(labels_test,threshold(clf.predict(data_test))))
    print('true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]')
    print("Precision and recall - ")
    print(precision_score(labels_test,threshold(clf.predict(data_test))))
    print(recall_score(labels_test,threshold(clf.predict(data_test))))
    print("f score - ")
    print(f1_score(labels_test,threshold(clf.predict(data_test))))
    return clf




def check_region(x):
    China_participants = np.array(csv.loc[(csv['Country']=='China'),['ParticipantID']])
    China_participants = [str(i[0]) for i in China_participants]
    #RoW_participants = np.array(csv.loc[(csv['Country']!='China') & (csv['Country']!='-'),['ParticipantID']])
    RoW_participants = np.array(csv.loc[(csv['Country']=='Индия',['ParticipantID'])])
    RoW_participants =  [str(i[0]) for i in RoW_participants]
    if x in China_participants:
        return 0
    elif x in RoW_participants:
        return 1
    else:
        return 2
    
def get_stats_csv():
    contest_list = ['Contest1236','Contest1243','Contest1244','Contest1245','Contest1248']
    csv_list=[]
    for i in contest_list:
        csv_list.append(pd.read_csv('../Data/'+str(i)+'/standings_statistics.csv',sep='\t'))
    csv = pd.concat(csv_list,sort=True)
    return csv
    
    
    
    
    
def check_rating(x):
    #print('Looking up rating....')

    blue_participants = np.array(csv.loc[(csv['Color']=='blue'),['ParticipantID']])
    blue_participants = [str(i[0]) for i in blue_participants]
    cyan_participants = np.array(csv.loc[(csv['Color']=='cyan'),['ParticipantID']]) #& (csv['Country']!='-'),['ParticipantID']])
    cyan_participants =  [str(i[0]) for i in cyan_participants]
    violet_participants = np.array(csv.loc[(csv['Color']=='violet'),['ParticipantID']]) #& (csv['Country']!='-'),['ParticipantID']])
    violet_participants =  [str(i[0]) for i in violet_participants]
    #print("   rating lists generated")
    if x in blue_participants:
        return 0
    elif x in violet_participants:
        return 1
    else :
        return 2

def prepare_data(g_truth,stopwords_flag):
    cols=['i', '=', 'int', '#', '1', '0', 'n', '.', 'define', '<', 'a', 'x', '<<', '+', 'if', '-', 'll', '()', '++', '>', 'for', 'include', 'b', 'return', 'j', 'long', '>>', '==', '*', '2', 'v', '&', 'c', 'y', 'k', 'ans', 'cin', 'cout', '<=', '%', 'const', 'm', 'T', 'p', 's', 'using', 't', 'std', 'vector', 'else', 'u', 'typedef', 'd', '+=', 'namespace', 'r', 'while', 'N', 'main', 'l', '3', 'f', 'endl', 'void', '/', '::', 'push_back', 'first', 'second', 'size', '<bits/stdc++.h>', 'mod', 'dp', '--', ':', '!=', 'res', '&&', 'pair', 'scanf', 'printf', 'template', 'e', 'cnt', 'w', 'pb', 'tie', 'q', 'ch', 'typename', 'g', 'bool', 'it', 'auto', '>=', 'false', 'sum', 'LL', 'max', 'inline', '!', 'sync_with_stdio', 'double', 'maxn', 'class', 'char', 'long long', 'read', 'MOD', 'begin', 'A', '10', 'break;', 'end', 'rep', '" "', '"%d"', "'\\n'", '...', 'mp', 'pii', 'dfs', '?', 'tmp', 'min', 'getchar', "'0'", 'st', 'sort', 'continue;', 'string', '||', 'cost', '7', '1e9', 'make_pair', 'z', 'solve', 'operator', '"\\n"', '-=', 'all', 'pos', 'ostream', 'os', 'S', 'sz', '<iostream>', 'abs', 'M', '<algorithm>', 'ret', 'ios_base', 'MAXN', 'now', 'arr', 'col', 'ld', 'val', 'true', 'cur', '4', 'find', 'to', 'INF', 'num', "' '", 'vis', 'temp', 'fi', 'vi', 'endif', '5', 'mn', 'se', 'edge', 'out', '1000000007', 'insert', 'gcd', 'F', '<vector>', 'ios', 'B', 'freopen', 'ss', 'R', 'fa', 'par', '<cstdio>', 'P', '%=', 'L', 'id', 'pll', 'root', '1e5', 'inf', '/=', 'pragma', 'mid', "'1'", 'mx', 'C', 'set', 'tot', 'node', "'9'", 'X', 'h', 'adj', '<queue>', 'c2', "'-'", '<map>', 'swap', '<set>', 'c1', 'in', '<cmath>', 'struct', '"%lld\\n"', 'GCC', 'ff', '6', 'signed', 'edges', '100005', '<cstring>', 'stdin', 'G', 'p1', 'FOR', 'vec', '"%lld"', 'return;', 'NULL', 'REP', 'cerr', 'ans1', '1ll', 'o', 'ifdef', 'V', 'K', 'push', 'str', 'erase', '->', '<string>', 'pr', 'U', 'ull', 'color', 'unsigned', '"r"', 'flag', 'ii', '"%d\\n"', 'count', '*=', 'top', 'xx', 'optimize', 'pre', 'get', 'pi', '1e18', 'ans2', 'E', 'puts', 'dist', 'Y', 'nxt', 'fr', 'T1', 'p2', 'len', 'map', 'empty', '[]', 'x1', '1LL', 'lli', 'parent', 'dis', 'add', 'sc', 's1', '<stack>', 'T2', 'print', 'resize', 'stdout', 'used', 'lower_bound', 'head', 'idx', 'PI', 'long double', 'sizeof', 'vll', 'deg', '^', '"-1"', "'('", 're', '", "', 'isdigit', 'debug', 'curr', 'ifndef', 'tree', 'memset', 't1', 'mi', 'a1', 'pair<int,int>', 's2', 'args', '>>=', 'istream', 'dir', 'ind', 'to_string', 'left', '"%d%d"', 'ONLINE_JUDGE', 'putchar', 'eps', '"w"', 'fib', '"-1\\n"', 'power', 'pop', 'right', 'yy', 'upper_bound', 'sum1', 'back', 'ar', 'MAX', 'register', 'names', '<iomanip>', '"%d %d\\n"', 'db', 't2', 'sum2', 'Edge', '""', '<bitset>', 'ok', 'emplace_back', 'pq', '__gcd', 'check', 'start', 'cnt1', 'rt', 'vl', '48', 'x2', 'graph', 'cnt2', 'y1', '0x3f3f3f3f', 'a2', '"%d "', 'tt', 'row', 'cmp', '"input.txt"', 'Q', 'md', '{}', 'int32_t', 'init', '__gnu_pbds', 'D', '2005', 'Args', 'from', 'write', 'base', 'last', 'Arg1', 'pp', 'acos', '<unordered_map>', 'ed', '<ext/pb_ds/assoc_container.hpp>', 'next', 'nullptr', '1e6', 'prime', 'front', 'long long int', 'forn', '100010']
    if g_truth=='rating':
        contest_list = ['Contest1236','Contest1243','Contest1244','Contest1245','Contest1248']
        token_data_list=[]
        for i in contest_list:
            token_data_list.append(pd.read_csv('../Data/'+str(i)+'/tokens_stats.txt',sep=' ',header=None,skiprows=1,names=cols))
        token_data = pd.concat(token_data_list)
        token_data = (token_data - token_data.mean())/token_data.std()
        print("core token data generated")
        print(token_data.shape)
        code_files = list(token_data.index)
        pid = [ i.split('_')[0] for i in code_files]
        token_data_2 = token_data.assign(pid=pid) 
        print("participant_id added")
        print("looking up rating....")
        token_data_2['rating'] = token_data_2['pid'].apply(check_rating)
        print("rating looked-up successfully")
        if stopwords_flag:
            stopwords=['ans', 'm', 'T', 'p', 's', 't',  'u',  'd',  'r',  'N',  'l', '3', 'f', 'dp', 'res',  'e', 'cnt', 'w', 'q', 'ch','g', 'it',   'A', '10', 'tmp', 'st', '7', '1e9',  'z',  'all', 'S', 'sz',  'M', 'MAXN', 'now', 'arr', 'col',  'val', 'cur', '4', 'num',  'vis', 'temp', '5', 'mn', 'se', 'F','B', 'ss', 'R', 'fa', 'par', 'P', 'L', 'id', 'root', '1e5', 'inf', 'mid', "'1'", 'mx', 'C', 'tot', 'node', "'9'", 'X', 'h', 'adj', 'c2', 'c1',  '6',  'edges', '100005', 'G', 'p1', 'vec','ans1','o', 'V', 'K', 'pr', 'color','flag',  'count','top', 'xx',  'pre', 'ans2', 'E', 'dist', 'Y', 'T1', 'p2', 'len', 'x1','parent', 'sc', 's1',  'T2',   'head', 'idx', 'PI', 'deg', '^', '"-1"', "'('", '", "', 'curr', 'tree',  't1', 'mi', 'a1','s2', 'dir', 'ind',  'left',  'eps', '"w"', 'fib', '"-1\\n"',  'right', 'yy', 'sum1', 'ar' , 'names', 'db', 't2', 'sum2', 'Edge', '""', 'ok', 'check', 'start', 'cnt1', 'rt', 'vl', '48', 'x2', 'graph', 'cnt2', 'y1','0x3f3f3f3f','a2',  'tt', 'row', 'cmp', '"input.txt"', 'Q', 'md',  'D', '2005', 'Args', '1e6',  'forn', '100010','k','c','x','i']
            for i in stopwords:
                token_data_2.drop(i,axis=1,inplace=True)
            print("stop words removed")
        
        token_data_2 = token_data_2[token_data_2.rating != 2]
        token_data_2.drop('pid',axis=1,inplace=True)
        col_red = token_data_2.columns
        x = token_data_2.iloc[:,:token_data_2.shape[1]-1]
        y = token_data_2.iloc[:,token_data_2.shape[1]-1:]
        y = np.array(y)
        y = [y[i][0] for i in range(len(y))]
        y=np.array(y)
        return x,y,col_red
    elif g_truth=='country':
        contest_list = ['Contest1236','Contest1243','Contest1244','Contest1245','Contest1248']
        token_data_list=[]
        for i in contest_list:
            token_data_list.append(pd.read_csv('../Data/'+str(i)+'/tokens_stats.txt',sep=' ',header=None,skiprows=1,names=cols))
        token_data = pd.concat(token_data_list)
        token_data = (token_data - token_data.mean())/token_data.std()
        print("core token data generated")
        print(token_data.shape)
        code_files = list(token_data.index)
        pid = [ i.split('_')[0] for i in code_files]
        token_data_2 = token_data.assign(pid=pid) 
        print("participant_id added")
        print("looking up region...........")
        token_data_2['region'] = token_data_2['pid'].apply(check_region)
        print("region looked up")
        if stopwords_flag:
            stopwords=['ans', 'm', 'T', 'p', 's', 't',  'u',  'd',  'r',  'N',  'l', '3', 'f', 'dp', 'res',  'e', 'cnt', 'w', 'q', 'ch','g', 'it',   'A', '10', 'tmp', 'st', '7', '1e9',  'z',  'all', 'S', 'sz',  'M', 'MAXN', 'now', 'arr', 'col',  'val', 'cur', '4', 'num',  'vis', 'temp', '5', 'mn', 'se', 'F','B', 'ss', 'R', 'fa', 'par', 'P', 'L', 'id', 'root', '1e5', 'inf', 'mid', "'1'", 'mx', 'C', 'tot', 'node', "'9'", 'X', 'h', 'adj', 'c2', 'c1',  '6',  'edges', '100005', 'G', 'p1', 'vec','ans1','o', 'V', 'K', 'pr', 'color','flag',  'count','top', 'xx',  'pre', 'ans2', 'E', 'dist', 'Y', 'T1', 'p2', 'len', 'x1','parent', 'sc', 's1',  'T2',   'head', 'idx', 'PI', 'deg', '^', '"-1"', "'('", '", "', 'curr', 'tree',  't1', 'mi', 'a1','s2', 'dir', 'ind',  'left',  'eps', '"w"', 'fib', '"-1\\n"',  'right', 'yy', 'sum1', 'ar' , 'names', 'db', 't2', 'sum2', 'Edge', '""', 'ok', 'check', 'start', 'cnt1', 'rt', 'vl', '48', 'x2', 'graph', 'cnt2', 'y1','0x3f3f3f3f','a2',  'tt', 'row', 'cmp', '"input.txt"', 'Q', 'md',  'D', '2005', 'Args', '1e6',  'forn', '100010','k','c','x','i']
            for i in stopwords:
                token_data_2.drop(i,axis=1,inplace=True)
            print("stop words removed")
        token_data_2 = token_data_2[token_data_2.region != 2]
        token_data_2.drop('pid',axis=1,inplace=True)
        col_red = token_data_2.columns
        x = token_data_2.iloc[:,:token_data_2.shape[1]-1]
        y = token_data_2.iloc[:,token_data_2.shape[1]-1:]
        y = np.array(y)
        y = [y[i][0] for i in range(len(y))]
        y=np.array(y)
        return x,y,col_red
       
        


## Ground Truth = Rating

In [324]:
csv=get_stats_csv()
x_rating,y_rating,token_col=prepare_data('rating',False)   #(g_truth,stopwords_flag)

core token data generated
(17866, 400)
participant_id added
looking up rating....
rating looked-up successfully


In [325]:
x_train_rating,y_train_rating,x_test_rating,y_test_rating,class_weight = train_test_split(x_rating,y_rating,2,0.6)

#### random forest

In [326]:
rf = rf_model(x_train_rating,y_train_rating,x_test_rating,y_test_rating,class_weight)

Training accuracy-
1.0
Testing accuracy-
0.7756247736327417
Confusion matrix -
[[4244   45]
 [1194   39]]
true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]
Precision and recall - 
0.4642857142857143
0.031630170316301706


#### logistic regression

In [364]:
lg_rating = log_reg_model(x_train_rating,y_train_rating,x_test_rating,y_test_rating,2,class_weight)

Training accuracy-
0.7386528247223564
Testing accuracy-
0.6218761318362912
Confusion matrix -
[[3053 1236]
 [ 852  381]]
true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]
Precision and recall - 
0.23562152133580705
0.30900243309002434
f1-score - 
0.2673684210526316


#### light gbm

In [365]:
lgbm_rating = light_gbm_model(x_train_rating,y_train_rating,x_test_rating,y_test_rating,class_weight)

Training accuracy-
0.8891839690970545
Testing accuracy-
0.7142339731981167
Confusion matrix -
[[3720  569]
 [1009  224]]
true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]
Precision and recall - 
0.28247162673392184
0.1816707218167072
f score - 
0.2211253701875617


In [329]:
x_train_rating.shape

(8284, 400)

Neural Network

In [366]:
model = Sequential()
model.add(Dense(100, input_dim=400, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(100, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(100, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(x_train_rating, y_train_rating,
          epochs=100,
          batch_size=128)
#score = model.evaluate(x_test_rating, y_test_rating, batch_size=128)
pred_rating_prob = model.predict(x_test_rating)
pred_y_test = [1 if i>0.5 else 0 for i in pred_rating_prob]



Epoch 1/100
8284/8284 [==============================] - 0s 39us/step - loss: 0.6315 - accuracy: 0.7374
Epoch 2/100
8284/8284 [==============================] - 0s 23us/step - loss: 0.5437 - accuracy: 0.7734
Epoch 3/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.4932 - accuracy: 0.7803
Epoch 4/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.4628 - accuracy: 0.7919
Epoch 5/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.4366 - accuracy: 0.7932
Epoch 6/100
8284/8284 [==============================] - 0s 24us/step - loss: 0.4225 - accuracy: 0.7976
Epoch 7/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.4070 - accuracy: 0.8076
Epoch 8/100
8284/8284 [==============================] - 0s 23us/step - loss: 0.3952 - accuracy: 0.8118
Epoch 9/100
8284/8284 [==============================] - 0s 24us/step - loss: 0.3814 - accuracy: 0.8180
Epoch 10/100
8284/8284 [==============================] - 0s 23u

8284/8284 [==============================] - 0s 23us/step - loss: 0.1199 - accuracy: 0.9587
Epoch 80/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.1229 - accuracy: 0.9623
Epoch 81/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.1067 - accuracy: 0.9657
Epoch 82/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.1242 - accuracy: 0.9625
Epoch 83/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.1224 - accuracy: 0.9577
Epoch 84/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.1155 - accuracy: 0.9597
Epoch 85/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.1198 - accuracy: 0.9588
Epoch 86/100
8284/8284 [==============================] - 0s 22us/step - loss: 0.1151 - accuracy: 0.9619
Epoch 87/100
8284/8284 [==============================] - 0s 23us/step - loss: 0.1112 - accuracy: 0.9623
Epoch 88/100
8284/8284 [==============================] - 0s 22us/st

In [367]:
print("Testing accuracy-")
print(accuracy_score(y_test_rating,pred_y_test))
print("Confusion matrix -")
print(confusion_matrix(y_test_rating,pred_y_test))
print('true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]')
print("Precision and recall - ")
print(precision_score(y_test_rating,pred_y_test))
print(recall_score(y_test_rating,pred_y_test))
print(f1_score(y_test_rating,pred_y_test))

Testing accuracy-
0.6566461427019196
Confusion matrix -
[[3133 1156]
 [ 740  493]]
true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]
Precision and recall - 
0.29896907216494845
0.39983779399837793
0.34212352532963214


## Ground Truth = Country

In [ ]:
x_country,y_country,token_col=prepare_data('country',True)

In [357]:
np.bincount(y_country)

array([2928, 2356])

In [358]:
token_col

Index(['=', 'int', '#', '1', '0', 'n', '.', 'define', '<', 'a',
       ...
       'acos', '<unordered_map>', 'ed', '<ext/pb_ds/assoc_container.hpp>',
       'next', 'nullptr', 'prime', 'front', 'long long int', 'region'],
      dtype='object', length=242)

In [359]:
x_train_country,y_train_country,x_test_country,y_test_country,class_weight_c = train_test_split(x_country,y_country,2,0.6)

#### random forest

In [360]:
rf_country = rf_model(x_train_country,y_train_country,x_test_country,y_test_country,class_weight_c)

Training accuracy-
1.0
Testing accuracy-
0.9214758751182592
Confusion matrix -
[[1343   79]
 [  87  605]]
true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]
Precision and recall - 
0.8845029239766082
0.8742774566473989
f1-score - 
0.8793604651162791


In [361]:
coeffecient_importance_country = rf_country.feature_importances_
f_imp_score_country={}
for i in range(len(token_col)-1):
    f_imp_score_country[token_col[i]]=coeffecient_importance_country[i]

In [362]:
import operator
sorted_f_imp_score_rating = sorted(f_imp_score_country.items(),key=operator.itemgetter(1),reverse=True)
sorted_f_imp_score_rating

[('long', 0.34393898621480057),
 ('.', 0.1551057706138652),
 ('-=', 0.07779933857146587),
 ('read', 0.028536894659908777),
 ('...', 0.02277012515169092),
 ('const', 0.016827456174676615),
 ('cost', 0.0151720529187675),
 ('j', 0.012347480194166361),
 ('<queue>', 0.012310993702204828),
 ('||', 0.011607144621383405),
 ('swap', 0.009855989772179075),
 ('sum', 0.009765000647609462),
 ('min', 0.009612693765711193),
 ('::', 0.00893135028474034),
 ('int', 0.006363057576747174),
 ('=', 0.006193551268523068),
 ('double', 0.006168848932751151),
 ('set', 0.006046690565070935),
 ('if', 0.005608097272176816),
 ('()', 0.00547548072041258),
 ('while', 0.005286515726306451),
 ('REP', 0.004842745178813464),
 ('0', 0.004298301160042305),
 ('<', 0.004267855846292394),
 ('power', 0.004265077892098843),
 ('#', 0.004152495361982641),
 ('"%d%d"', 0.004023057018647608),
 ('in', 0.00390782800569604),
 ('to_string', 0.0037782456923268048),
 ('to', 0.003563503835010059),
 ('else', 0.0035530330242808583),
 ('-', 0

#### logistic regression

In [351]:
log_ref_country = log_reg_model(x_train_country,y_train_country,x_test_country,y_test_country,2,class_weight_c)

Training accuracy-
0.9716088328075709
Testing accuracy-
0.9304635761589404
Confusion matrix -
[[1348   74]
 [  73  619]]
true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]
Precision and recall - 
0.8932178932178932
0.8945086705202312


#### light gbm

In [363]:
lgbm_country = light_gbm_model(x_train_country,y_train_country,x_test_country,y_test_country,class_weight)

Training accuracy-
0.9738170347003154
Testing accuracy-
0.9370860927152318
Confusion matrix -
[[1378   44]
 [  89  603]]
true negatives is C[0,0] , false negatives is C[1,0] , true positives is C[1,1]  and false positives is C[0,1]
Precision and recall - 
0.9319938176197836
0.8713872832369942
f score - 
0.9006721433905899
